import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {Poppins} from 'next/font/google' 

const poppins = Poppins ({subsets:['latin'], weight:['300','400','700','900']}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body 
      >
        {children}
      </body>
    </html>
  );
}
